# Generated by Django 5.1.3 on 2024-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.IntegerField(max_length=11, verbose_name='شماره تلفن')),
                ('fabric', models.CharField(max_length=200, verbose_name='مشخصات پارچه')),
                ('pants', models.CharField(max_length=200, verbose_name='مشخصات شلوار')),
                ('fabric_length1', models.FloatField(verbose_name='متراژ')),
                ('shirt', models.CharField(max_length=200, verbose_name='مشخصات پیراهن')),
                ('fabric_length2', models.FloatField(verbose_name='متراژ')),
                ('date', models.DateField(verbose_name='تاریخ تحویل')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='بیعانه')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='اجرت')),
                ('delivered', models.BooleanField(default=False, verbose_name='تحویل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
