# Generated by Django 5.1.3 on 2024-11-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khayyat', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fabric_length1',
            field=models.FloatField(verbose_name='متراژ(متر)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_length2',
            field=models.FloatField(verbose_name='متراژ(متر)'),
        ),
    ]
