# Generated by Django 5.1.3 on 2024-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khayyat', '0005_alter_order_deposit_alter_order_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=10, verbose_name='تاریخ تحویل'),
        ),
    ]
