# Generated by Django 5.1.3 on 2024-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khayyat', '0006_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fabric_length1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric_length2',
        ),
        migrations.AddField(
            model_name='order',
            name='fabric_length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ'),
        ),
    ]
