# Generated by Django 5.1.3 on 2024-12-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khayyat', '0008_alter_order_date_alter_order_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pants',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shirt',
        ),
        migrations.AddField(
            model_name='order',
            name='entry_date',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_crotch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='فاق شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_fabric',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='پارچه شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_fabric_length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ پارچه شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_hem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دمپای شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_knee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زانو شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قد شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_thigh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ران شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='pants_waist',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کمر شلوار'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_armpit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زیر بغل پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_collar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='یقه پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_fabric',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='پارچه پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_fabric_length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ پارچه پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قد پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_shoulder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سرشانه پیراهن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shirt_sleeve',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آستین پیراهن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='آیا تحویل داده شده است؟'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='بیعانه (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wage',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='اجرت (تومان)'),
        ),
    ]
